/**
 * Prebuild script: reads CSS from node_modules (bootstrap, formiojs, font-awesome),
 * inlines woff2 + woff font files as base64 data URIs, scopes selectors, and
 * writes ready-to-inject CSS modules to src/styles/generated/.
 *
 * Run with: node scripts/prebuild-css.cjs
 */

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const OUT_DIR = path.join(ROOT, 'src', 'styles', 'generated')

const SCOPE_MAIN = '.bootstrap-scope, .formio-builder, .formbuilder'
const SCOPE_DIALOGS = '.formio-modal, .formio-dialog, .formio-edit-form, .formio-builder-dialog, .modal'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const MIME = {
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
}

/** Read a font file and return a data-URI string, or null if not found. */
function toDataUri(filePath) {
  if (!fs.existsSync(filePath)) return null
  const ext = path.extname(filePath).toLowerCase()
  const mime = MIME[ext]
  if (!mime) return null
  const b64 = fs.readFileSync(filePath).toString('base64')
  return `data:${mime};base64,${b64}`
}

/**
 * Replace a multi-format @font-face src list with woff2+woff data URIs.
 * Works on both minified and formatted CSS.
 */
function rewriteFontFace(css, fontMap) {
  return css.replace(/@font-face\s*\{[^}]+\}/gi, (block) => {
    let replaced = false
    for (const [namePattern, { woff2, woff }] of Object.entries(fontMap)) {
      if (!block.includes(namePattern)) continue
      const srcParts = []
      if (woff2) srcParts.push(`url('${woff2}') format('woff2')`)
      if (woff) srcParts.push(`url('${woff}') format('woff')`)
      if (srcParts.length === 0) continue

      block = block.replace(/src\s*:[^;}]+[;}]/g, (srcDecl) => {
        const endsWithBrace = srcDecl.endsWith('}')
        if (!replaced) {
          replaced = true
          return `src:${srcParts.join(',')};` + (endsWithBrace ? '}' : '')
        }
        return endsWithBrace ? '}' : ''
      })
    }
    return block
  })
}

/** Strip sourceMappingURL comments. */
function stripSourceMapComments(css) {
  return css
    .replace(/\/\*# sourceMappingURL=.*?\*\//g, '')
    .replace(/\/\/# sourceMappingURL=.*$/gm, '')
}

/**
 * Scope CSS selectors under the given scope string.
 * Uses :is() to combine multiple scopes into one selector, avoiding
 * selector multiplication (3 scopes × N selectors → just 1 × N).
 */
function scopeCss(css, scope) {
  const scopes = scope.split(',').map((s) => s.trim()).filter(Boolean)
  // Use :is() to merge multiple scopes into one efficient selector
  const scopeSelector = scopes.length === 1 ? scopes[0] : `:is(${scopes.join(', ')})`

  return css.replace(
    /([^{}]*?)\{/g,
    (match, rawSelectors) => {
      const trimmed = rawSelectors.trim()
      if (!trimmed || trimmed.startsWith('@')) return match

      const selectors = trimmed.split(',').map((s) => s.trim()).filter(Boolean)
      const prefixed = selectors.map((sel) => {
        if (/^(?:from|to|\d+%)$/.test(sel)) return sel
        return `${scopeSelector} ${sel}`
      })
      return prefixed.join(', ') + ' {'
    },
  )
}

// ---------------------------------------------------------------------------
// Font data URIs
// ---------------------------------------------------------------------------

const FA_FONTS = path.join(ROOT, 'node_modules', 'font-awesome', 'fonts')
const BS_FONTS = path.join(ROOT, 'node_modules', 'bootstrap', 'dist', 'fonts')

const fontAwesomeDataUris = {
  woff2: toDataUri(path.join(FA_FONTS, 'fontawesome-webfont.woff2')),
  woff: toDataUri(path.join(FA_FONTS, 'fontawesome-webfont.woff')),
}

const glyphiconsDataUris = {
  woff2: toDataUri(path.join(BS_FONTS, 'glyphicons-halflings-regular.woff2')),
  woff: toDataUri(path.join(BS_FONTS, 'glyphicons-halflings-regular.woff')),
}

// ---------------------------------------------------------------------------
// Process CSS files
// ---------------------------------------------------------------------------

fs.mkdirSync(OUT_DIR, { recursive: true })

/** Escape backticks and backslashes for template literal embedding. */
function escapeForTemplate(str) {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

/** Write CSS as an exported TypeScript string constant. */
function writeCssModule(filename, css) {
  const code = `// Auto-generated by scripts/prebuild-css.cjs — do not edit\nexport default \`${escapeForTemplate(css)}\`;\n`
  fs.writeFileSync(path.join(OUT_DIR, filename), code)
}

// 1. Bootstrap CSS — inline Glyphicons
const bootstrapCssPath = path.join(ROOT, 'node_modules', 'bootstrap', 'dist', 'css', 'bootstrap.min.css')
let bootstrapCss = fs.readFileSync(bootstrapCssPath, 'utf8')
bootstrapCss = stripSourceMapComments(rewriteFontFace(bootstrapCss, {
  'glyphicons-halflings-regular': glyphiconsDataUris,
}))

// 2. Formio CSS — inline FontAwesome
const formioCssPath = path.join(ROOT, 'node_modules', 'formiojs', 'dist', 'formio.full.min.css')
let formioCss = fs.readFileSync(formioCssPath, 'utf8')
formioCss = stripSourceMapComments(rewriteFontFace(formioCss, {
  'fontawesome-webfont': fontAwesomeDataUris,
}))

// 3. Font Awesome CSS — inline its own fonts
const fontAwesomeCssPath = path.join(ROOT, 'node_modules', 'font-awesome', 'css', 'font-awesome.css')
let fontAwesomeCss = fs.readFileSync(fontAwesomeCssPath, 'utf8')
fontAwesomeCss = stripSourceMapComments(rewriteFontFace(fontAwesomeCss, {
  'fontawesome-webfont': fontAwesomeDataUris,
}))

// ---------------------------------------------------------------------------
// Strip @font-face blocks from CSS, collect them separately.
// This avoids duplicating 100KB+ base64 data URIs across scoped modules.
// ---------------------------------------------------------------------------

function extractFontFaces(css) {
  const fontFaces = []
  const stripped = css.replace(/@font-face\s*\{[^}]+\}/gi, (block) => {
    fontFaces.push(block)
    return ''
  })
  return { css: stripped, fontFaces }
}

const bsExtracted = extractFontFaces(bootstrapCss)
const fiExtracted = extractFontFaces(formioCss)
const faExtracted = extractFontFaces(fontAwesomeCss)

// Deduplicate font-face blocks (formio and font-awesome both ship the same FontAwesome @font-face)
const allFontFaces = new Set()
;[...bsExtracted.fontFaces, ...fiExtracted.fontFaces, ...faExtracted.fontFaces].forEach((ff) => {
  allFontFaces.add(ff)
})

const bootstrapRules = bsExtracted.css
const formioRules = fiExtracted.css
const fontAwesomeRules = faExtracted.css

// ---------------------------------------------------------------------------
// Pre-scope CSS at build time (was previously done on every page load)
// ---------------------------------------------------------------------------

const isolationCss = `
.formio-dialog { position: fixed; top: 0; left: 0; right: 0; bottom: 0; width: 100%; height: 100%; z-index: 99999; overflow-y: auto; -webkit-overflow-scrolling: touch; }
.formio-dialog-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.4); z-index: -1; }
.formio-dialog-content { position: relative; background: #fff; margin: 5vh auto; width: 80%; max-width: 900px; padding: 20px; border-radius: 4px; border: none; box-shadow: 0 4px 20px rgba(0,0,0,0.3); }
.formio-dialog-close { position: absolute; top: 0; right: 0; padding: 10px; cursor: pointer; font-size: 24px; line-height: 1; background: transparent; border: none; color: #333; z-index: 1; }
.formio-dialog .nav-tabs { display: flex !important; flex-wrap: nowrap !important; list-style: none; padding: 0; margin: 0 0 10px; border-bottom: 1px solid #ddd; }
.formio-dialog .nav-tabs > li { float: none !important; margin-bottom: -1px; white-space: nowrap; }
.formio-dialog .nav-tabs > li > a { display: block; padding: 8px 12px; font-size: 13px; text-decoration: none; color: #337ab7; border: 1px solid transparent; border-radius: 4px 4px 0 0; }
.formio-dialog .nav-tabs > li.active > a { color: #555; background-color: #fff; border: 1px solid #ddd; border-bottom-color: transparent; }
.formio-dialog .ace_editor { all: initial !important; position: relative !important; display: block !important; font-family: monospace !important; font-size: 12px !important; line-height: normal !important; height: 100px !important; min-height: 100px !important; width: 100% !important; border: 1px solid #ccc !important; background: #fff !important; color: #000 !important; overflow: hidden !important; direction: ltr !important; text-align: left !important; }
.formio-dialog .ace_editor * { all: revert !important; }
`

const extraCss = `
.bootstrap-scope { isolation: isolate; contain: layout style paint; }
.formio-modal, .formio-dialog, .formio-edit-form, .formio-builder-dialog, .modal { isolation: isolate; }
`

// font-faces module — all @font-face blocks, deduplicated, emitted ONCE
writeCssModule('font-faces.ts', [...allFontFaces].join('\n'))
console.log('  ✓ font-faces.ts (deduplicated @font-face blocks)')

writeCssModule('isolation.ts', isolationCss)
console.log('  ✓ isolation.ts')

writeCssModule('bootstrap-main.ts', scopeCss(bootstrapRules, SCOPE_MAIN) + extraCss)
console.log('  ✓ bootstrap-main.ts (scoped to SCOPE_MAIN)')

writeCssModule('bootstrap-dialogs.ts',
  scopeCss(bootstrapRules, SCOPE_DIALOGS) + scopeCss(formioRules, SCOPE_DIALOGS))
console.log('  ✓ bootstrap-dialogs.ts (scoped to SCOPE_DIALOGS)')

writeCssModule('formio-main.ts', scopeCss(formioRules, SCOPE_MAIN))
console.log('  ✓ formio-main.ts (scoped to SCOPE_MAIN)')

writeCssModule('font-awesome-scoped.ts',
  scopeCss(fontAwesomeRules, SCOPE_MAIN) + scopeCss(fontAwesomeRules, SCOPE_DIALOGS))
console.log('  ✓ font-awesome-scoped.ts (scoped to both)')

console.log('prebuild-css: done')
